### ISSUE TITLE
Planificación

### ISSUE THREAD

**Issue by lissavcasas** [marimeli/lim-2018-05-bc-core-pm-datadashboard#9]
- [x] **Desarrollar Product Backlog  con el squad.**

- [x] **Forkear el proyecto Datadashboard.**

**Configurar el ambiente de trabajo:**
- [x]  Instalar Figma.
- [x] Crear una cuenta en Trello.
- [x] Crear tablero para sprint1.
- [x] Crear ramas de trabajo en Github (develop y gh-pages)

 **Repasar los principales temas relacionados:**  
- [x] Arrays y sus métodos.
- [x] Objects y sus métodos.
- [x] XHR.
- [x] Fetch. 
- [x] DOM.
- [x] BOM.
- [x] Funciones
- [x] Diferencia de cons y let.
- [x] Estructuras condicionales y repetitivas (bucles).
- [x] Bootstrap.
- [x] Fundamentos UX.
- [x] Visual Design.

- [x] **Tener clara la rúbrica para trabajar en base a los niveles esperados.**

**Comment by natachang** [comment]
Asignaciones

**Comment by lissavcasas** [comment]
Nat, nos falta sacar el enlace de nuestro prototipo en Figma para ponerlo en el read me.
Don't forget about it!

**Comment by lissavcasas** [comment]
PDT: Encontré buena info para reforzar nuestros conocimientos en peticiones AJAX. 👍 
[https://datyayu.xyz/blog/posts/fetch-api](url)
